### ISSUE TITLE
Version 1.2.8 of XamlControlsResources lacks parameters.

### ISSUE THREAD

**Issue by Youcheng-cat** [iNKORE-NET/UI.WPF#2]
Briefly speaking, based on the documentation, I discovered that after the update to version 1.2.8, when the <ui:XamlControlsResources /> in App.xaml was instantiated and executed, an exception was thrown:
FormatException: TopLeftValue is not a valid value for CornerRadiusFilterKind.

ArgumentException: Requested value 'TopLeftValue' was not found.
I have been speculating for a long time but still have no idea where the problem lies.

**Comment by mmashwani** [comment]
While remaining on 1.2.8 for UI.WPF, I rolled UI.WPF.Modern back one by one and found that the error goes away with 0.9.26.

```
<PackageReference Include="iNKORE.UI.WPF" Version="1.2.8" />
<PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.9.26" />
```

**Comment by Youcheng-cat** [comment]
I am writing to inform you that I have been able to use the latest version of UI.WPF.Modern without issues. Additionally, I noticed that the bug present in UI.WPF version 1.2.7.1 has been resolved. It appears that version 1.2.8, which I believe contained the erroneous behavior, is no longer available on NuGet. Thank you for addressing this matter!

Thank you for your response!

These responses were translated using an AI translator; please bear with any inaccuracies.

**Comment by Youcheng-cat** [comment]
> 同时保留 1.2.8 的 UI 版本。WPF，我滚动了 UI。WPF 的 WPF 中。Modern 一一返回，发现错误在 0.9.26 消失。
> 
> ```
> <PackageReference Include="iNKORE.UI.WPF" Version="1.2.8" />
> <PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.9.26" />
> ```


I am writing to inform you that I have been able to use the latest version of UI.WPF.Modern without issues. Additionally, I noticed that the bug present in UI.WPF version 1.2.7.1 has been resolved. It appears that version 1.2.8, which I believe contained the erroneous behavior, is no longer available on NuGet. Thank you for addressing this matter!

Thank you for your response!

These responses were translated using an AI translator; please bear with any inaccuracies.
